"""Folder layout rules for a document.

This module is the single authority on where anything belonging to a document
lives on disk. The Document Desk interface draws the same tree in its "Deposit"
view; if the two ever disagree, this file wins and the view is wrong.

Deliberately free of any web framework, filesystem side effects or app state:
everything here is a pure function over plain data, so it can be tested without
starting the application.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Iterable, Literal

__all__ = [
    "DOCUMENT_FILE",
    "DEPOSIT_FILE",
    "slug",
    "pad2",
    "SUBDOCS",
    "subdocs_for",
    "subdoc_filenames",
    "subdoc_filename",
    "figure_dir",
    "table_dir",
    "data_dir",
    "plot_csv",
    "equation_file",
    "equations_in_order",
    "PlannedPath",
    "plan_document",
    "document_root_name",
]

# The document's own state, mirrored into its folder. The vault indexes it;
# this file is what survives the vault.
DOCUMENT_FILE = "document.json"

# What the folder is, written for whoever opens the deposit rather than for the
# application. Generated by `deposit.compile_deposit`; never edited by hand.
DEPOSIT_FILE = "DEPOSIT.md"

_SLUG_STRIP = re.compile(r"[^a-z0-9]+")
_SLUG_EDGES = re.compile(r"^-+|-+$")

# Sub-documents by document kind. Mirrors SUBDOCS in the interface.
SUBDOCS: dict[str, list[tuple[str, str]]] = {
    "publication": [
        ("manuscript", "Manuscript"),
        ("si", "Supporting Information"),
        ("cover", "Cover Letter"),
        ("dmp", "Data Management"),
    ],
    "report": [
        ("manuscript", "Report"),
        ("si", "Appendices"),
        ("dmp", "Data Management"),
    ],
    "grant": [
        ("manuscript", "Case for Support"),
        ("si", "Justification of Resources"),
        ("cover", "Summary & Impact"),
        ("dmp", "Data Management"),
    ],
}

Kind = Literal["dir", "file"]


def slug(text: str, max_len: int = 60) -> str:
    """Lower-case, hyphen-separated, filesystem-safe. Never empty."""
    out = _SLUG_EDGES.sub("", _SLUG_STRIP.sub("-", (text or "").lower()))
    out = out[:max_len]
    out = _SLUG_EDGES.sub("", out)
    return out or "untitled"


def pad2(n: int) -> str:
    return f"{n:02d}"


def document_root_name(title: str) -> str:
    """Folder name for a document, from its title."""
    return slug(title, max_len=48)


def subdocs_for(document: dict) -> list[tuple[str, str]]:
    """The sub-documents a document is made of, as (key, label), in order.

    A grant defines its own: `grantParts` is the application's list of parts,
    in the order the funder asks for them, and each part is a sub-document
    with its own export. Every other kind — and a grant written before parts
    existed — uses the fixed list for its kind. Mirrors `subdocsOf()` in the
    interface.
    """
    kind = document.get("kind", "publication")
    parts = document.get("grantParts") if kind == "grant" else None
    if isinstance(parts, list):
        out = [(str(p["k"]), str(p.get("l") or p["k"]))
               for p in parts if isinstance(p, dict) and p.get("k")]
        if out:
            return out
    return list(SUBDOCS.get(kind, SUBDOCS["publication"]))


def subdoc_filenames(document: dict, ext: str = "docx") -> dict[str, str]:
    """Every sub-document's export file name, by key.

    Named after the label. Two parts a person has given the same name would
    otherwise plan the same file, so the second becomes `-2`, the third `-3`.
    """
    out: dict[str, str] = {}
    used: set[str] = set()
    for key, label in subdocs_for(document):
        stem = slug(label)
        name, n = stem, 1
        while name in used:
            n += 1
            name = f"{stem}-{n}"
        used.add(name)
        out[key] = f"{name}.{ext}"
    return out


def subdoc_filename(kind_or_document: str | dict, subdoc_key: str, ext: str = "docx") -> str:
    """`manuscript.docx`, `supporting-information.docx`, and so on.

    Pass the document itself where it is to hand: a grant names its own parts,
    so only the document knows that `g_x1y2z3a` is `vision-and-approach.docx`.
    A kind alone gives the fixed names for that kind.
    """
    if isinstance(kind_or_document, dict):
        document = kind_or_document
    else:
        document = {"kind": kind_or_document}
    names = subdoc_filenames(document, ext)
    if subdoc_key in names:
        return names[subdoc_key]
    return f"{slug(subdoc_key)}.{ext}"


def figure_dir(index: int) -> str:
    """1-based figure index -> `figures/figure-01`."""
    return f"figures/figure-{pad2(index)}"


def table_dir(index: int) -> str:
    """1-based table index -> `tables/table-01`."""
    return f"tables/table-{pad2(index)}"


def data_dir(target_kind: Literal["figure", "table", "plot"], index: int) -> str:
    """Where raw data attached to a figure or table is filed."""
    return f"data/{target_kind}-{pad2(index)}"


def plot_csv(ref: str) -> str:
    """A plot's own numbers, one column per series -> `plots/P1.csv`.

    The reference is used verbatim: this module plans, it does not sanitise.
    Anything written to the path goes through `resolve_within`, which is what
    refuses a reference that would climb out of the folder.
    """
    return f"plots/{ref}.csv"


def equation_file(index: int) -> str:
    """1-based equation index -> `equations/equation-01.tex`."""
    return f"equations/equation-{pad2(index)}.tex"


def equations_in_order(document: dict) -> list[dict]:
    """Every equation block in the document, in reading order.

    Sub-documents are walked in the order the document declares them (its
    kind's fixed list, or a grant's own parts), then sections, then blocks —
    the same order the interface numbers them in, so
    `equations/equation-03.tex` is the third equation a reader meets.
    Unnumbered equations are included: they are still part of the record.
    """
    out: list[dict] = []
    subdocs = document.get("subdocs") or {}
    keys = [k for k, _ in subdocs_for(document)]
    for key in keys + [k for k in subdocs if k not in keys]:
        sub = subdocs.get(key) or {}
        for section in sub.get("sections") or []:
            for block in section.get("blocks") or []:
                if isinstance(block, dict) and block.get("type") == "eq":
                    out.append(block)
    return out


def _equation_note(block: dict) -> str:
    label = str(block.get("label") or "").strip()
    state = "numbered" if block.get("numbered") is not False else "unnumbered"
    return f"{label} · {state}" if label else state


@dataclass(frozen=True)
class PlannedPath:
    path: str          # relative to the document root, POSIX separators
    kind: Kind
    note: str = ""     # human-readable annotation, shown in the interface
    generated: bool = False  # written by the app rather than by the user


def _fig_index(document: dict, ref: str) -> int | None:
    for i, f in enumerate(document.get("figures") or [], start=1):
        if f.get("ref") == ref:
            return i
    return None


def _tbl_index(document: dict, ref: str) -> int | None:
    for i, t in enumerate(document.get("tables") or [], start=1):
        if t.get("ref") == ref:
            return i
    return None


def _plot_index(document: dict, ref: str) -> int | None:
    for i, pl in enumerate(document.get("plots") or [], start=1):
        if pl.get("ref") == ref:
            return i
    return None


def attachment_dir(document: dict, target_ref: str) -> str:
    """Resolve an attachment's `target` ref (F1, T2, P3 ...) to its data folder.

    Plots are app-scoped while attachments are document-scoped, so a plot's raw
    data is filed under the document that attached it. That is the same
    app-versus-document tension as the reference library; see DOC-001.
    """
    fi = _fig_index(document, target_ref)
    if fi is not None:
        return data_dir("figure", fi)
    ti = _tbl_index(document, target_ref)
    if ti is not None:
        return data_dir("table", ti)
    pi = _plot_index(document, target_ref)
    if pi is not None:
        return data_dir("plot", pi)
    return "data/unassigned"


def plan_document(document: dict) -> list[PlannedPath]:
    """The complete folder plan for a document, in display order.

    `document` is the interface's state object. Only the keys used here matter:
    kind, grantParts, figures, tables, attachments, revisions, reviews, refs.
    """
    out: list[PlannedPath] = []

    # The document itself, as the interface holds it. Written on every save so
    # the folder is complete on its own and the vault can be rebuilt from it.
    out.append(PlannedPath(DOCUMENT_FILE, "file", note="the document", generated=True))

    for _key, name in subdoc_filenames(document).items():
        out.append(PlannedPath(name, "file", note="export", generated=True))

    figures = document.get("figures") or []
    out.append(PlannedPath("figures", "dir"))
    for i, fig in enumerate(figures, start=1):
        d = figure_dir(i)
        out.append(PlannedPath(d, "dir", note=fig.get("ref", "")))
        stem = d.rsplit("/", 1)[-1]
        ref = fig.get("ref", "")
        out.append(PlannedPath(f"{d}/{stem}.svg", "file",
                               note=f"figure {ref} (vector)", generated=True))
        out.append(PlannedPath(f"{d}/{stem}.png", "file",
                               note=f"figure {ref} (raster)", generated=True))
        for panel in fig.get("panels") or []:
            src_id = panel.get("src")
            if not src_id:
                continue
            out.append(PlannedPath(f"{d}/{src_id}.plotspec.json", "file",
                                   note=f"plot specification for {src_id}", generated=True))

    tables = document.get("tables") or []
    out.append(PlannedPath("tables", "dir"))
    for i, tbl in enumerate(tables, start=1):
        d = table_dir(i)
        out.append(PlannedPath(d, "dir", note=tbl.get("ref", "")))
        stem = d.rsplit("/", 1)[-1]
        out.append(PlannedPath(f"{d}/{stem}.csv", "file",
                               note=f"table {tbl.get('ref', '')}", generated=True))

    # A plot is app-scoped, but the numbers behind a panel belong with the work
    # being deposited, so every plot the document can reach is written out.
    plots = document.get("plots") or []
    out.append(PlannedPath("plots", "dir", note="plotted values"))
    for pl in plots:
        out.append(PlannedPath(plot_csv(pl.get("ref", "")), "file",
                               note=pl.get("name", ""), generated=True))

    equations = equations_in_order(document)
    out.append(PlannedPath("equations", "dir"))
    for i, block in enumerate(equations, start=1):
        out.append(PlannedPath(equation_file(i), "file",
                               note=_equation_note(block), generated=True))

    out.append(PlannedPath("data", "dir", note="deposition set"))
    grouped: dict[str, list[dict]] = {}
    for att in document.get("attachments") or []:
        grouped.setdefault(attachment_dir(document, att.get("target", "")), []).append(att)
    for d in sorted(grouped):
        out.append(PlannedPath(d, "dir"))
        for att in grouped[d]:
            out.append(PlannedPath(f"{d}/{att.get('name', 'file')}", "file",
                                   note=f"raw data for {att.get('target', 'unassigned')}"))
    out.append(PlannedPath("data/MANIFEST.csv", "file", note="generated", generated=True))
    out.append(PlannedPath("data/README.md", "file", note="generated", generated=True))

    out.append(PlannedPath("references", "dir"))
    out.append(PlannedPath("references/cited.ris", "file", generated=True))

    out.append(PlannedPath("drafts", "dir"))
    for i, rev in enumerate(document.get("revisions") or [], start=1):
        label = slug(rev.get("label", f"revision-{i}"))
        out.append(PlannedPath(f"drafts/rev-{pad2(i)}-{label}.json", "file",
                               note=rev.get("by", ""), generated=True))

    reviews = document.get("reviews") or []
    if reviews:
        out.append(PlannedPath("reviews", "dir"))
        for rv in reviews:
            out.append(PlannedPath(f"reviews/{slug(rv.get('reviewer', 'reviewer'))}.json",
                                   "file", generated=True))

    # Last, because it describes everything above it.
    out.append(PlannedPath(DEPOSIT_FILE, "file", note="what is in this folder", generated=True))

    return out


def directories(document: dict) -> list[str]:
    """Just the folders, deepest last — what `create_document_tree` makes."""
    seen: list[str] = []
    for p in plan_document(document):
        if p.kind == "dir" and p.path not in seen:
            seen.append(p.path)
    return seen


def iter_generated(document: dict) -> Iterable[PlannedPath]:
    return (p for p in plan_document(document) if p.generated)
